title: chenleyi
description: The head is always fooled by the heart.
author: chenleyi
avatar: /logo.jpg
email: chenleyi2001@gmail.com
skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10


# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================

logo: logo.png
social:
  name: chenleyi

# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
